server:
  port: 9981
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssms?useSSL=false
    username: root
    password: 123456
    schema: classpath:db-schema.sql
    data: classpath:db-data.sql
    continue-on-error: true # 数据库脚本执行失败的时候忽略错误继续启动程序
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.nwsuaf.cie.ssms.model
root:
  username: admin
  pswd: 5ff4b333705ff53f7c44e8a4b71a90bf # RootAuthUtil 生成的加密数据
properties:
  price:
    student: 8
    teacher: 15
  time:
    summer:
      start: '16:30'
      end: '22:00'
    winter:
      start: '16:00'
      end: '21:30'
    holiday:
      start: '15:00'
      end: '22:00'