server:
  port: 9981
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssms?useSSL=false
    username: root
    password: 123456
    schema: classpath:db-schema.sql
    data: classpath:db-data.sql
    continue-on-error: true # 数据库脚本执行失败的时候忽略错误继续启动程序
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.nwsuaf.cie.ssms.model
root:
  username: admin
  pswd: d14bd18d78cfe8fb709f4eafcbc4403a # RootAuthUtil 生成的加密数据